# Generated by Django 2.2.4 on 2019-09-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='publisher',
            field=models.TextField(null=True),
        ),
    ]
